Add guest_vlan_allowed property to routed and isolated VCD networks
vmware/terraform-provider-vcd pull request #1080
Opened 2023-07-10 14:42 UTC by s-winkelhofer

This PR enables the `guest_vlan_allowed` property on routed and isolated VCD networks (feature available on VCD 10.3.0+)

2023-07-12 09:36 UTC, adezxc requested changes
Hi @s-winkelhofer, thanks for your contribution!

A few comments: 
* Regarding @vmwclabot, you need to sign your commits with `Signed-off-by: John Doe <john.doe@email.org>` at the end of the commit message, you can also do that with the `-s` flag.
* We want to mention every feature/improvement/bugfix PR in the changelog, for that you should create a file in `.changes/v3.10.0`, see [here] for reference
* In this repo we also have the documentation for the Terraform registry, so you should document the new argument in all the resources/data sources that you changed, and add `guest_vlan_allowed` to the example configuration section.


If you have any questions, please don't hesitate to ask us how to proceed, thanks again!

[here]: https://github.com/vmware/terraform-provider-vcd/blob/main/.changes/v3.9.0/1010-improvements.md

2023-07-12 09:36 UTC, adezxc commented on vcd/resource_vcd_network_isolated_v2_nsxt_test.go
> +	}
For consistency we keep these configuration templates in line with Terraform style guidelines
```suggestion
  start_address = "1.1.1.10"
  end_address   = "1.1.1.20"
}
	
metadata = {
  {{.MetadataKey}} = "{{.MetadataValue}}"
}
```

2023-07-12 09:36 UTC, adezxc commented on vcd/resource_vcd_network_isolated_v2_nsxt_test.go
> +	description = "updated NSX-T isolated network test"
For consistency we keep these configuration templates in line with Terraform style guidelines
```suggestion
  org  = "{{.Org}}"
  vdc  = "{{.NsxtVdc}}"
	
  name        = "{{.NetworkName}}"
  description = "updated NSX-T isolated network test"
```

2023-07-12 09:36 UTC, adezxc commented on vcd/resource_vcd_network_routed_v2_nsxt_test.go
> +  guest_vlan_allowed = true
For consistency we keep these configuration templates in line with Terraform style guidelines
```suggestion
  gateway                    = "1.1.1.1"
  prefix_length            = 24
  guest_vlan_allowed = true
```

2023-07-12 09:36 UTC, adezxc commented on vcd/resource_vcd_network_isolated_v2_nsxt_test.go
> +	}
For consistency we keep these configuration templates in line with Terraform style guidelines
```suggestion
  start_address = "1.1.1.10"
  end_address   = "1.1.1.20"
}
```

2023-07-13 20:48 UTC, Didainius commented on vcd/datasource_vcd_network_routed_v2.go
> +				Optional:    true,
```suggestion
				Computed:    true,
```

2023-07-13 20:48 UTC, Didainius commented on vcd/datasource_vcd_network_routed.go
> +				Optional:    true,
```suggestion
				Computed:    true,
```

2023-07-13 20:48 UTC, Didainius commented on vcd/datasource_vcd_network_isolated_v2.go
> +				Optional:    true,
```suggestion
				Computed:    true,
```

2023-07-13 20:49 UTC, Didainius commented on vcd/datasource_vcd_network_isolated.go
> +				Optional:    true,
```suggestion
				Computed:    true,
```

2023-07-19 09:57 UTC, s-winkelhofer commented
Thanks for the review, I updated the branch, so it covers all your suggested changes.

2023-07-25 08:18 UTC, adezxc approved these changes
Looks good to me, tested the change manually, thanks for the PR!

2023-07-26 06:09 UTC, Didainius commented
@s-winkelhofer ,
Thanks for the adjustments! I wanted to clarify a general thing as it is valuable feedback. The `_v2` resources are made for the replacement of previous resources (non `_v2`) so I am curious - are you still actively using any of the `vcd_network_routed` or `vcd_network_isolated`?

2023-07-30 23:21 UTC, s-winkelhofer commented
@Didainius thank you. We are only using the `_v2` resources. I added the feature to the `non _v2` resources for completeness reasons.

2023-08-07 06:01 UTC, dataclouder commented on website/docs/r/network_isolated.html.markdown
> +* `guest_vlan_allowed` - (Optional) True if Network allows guest VLAN tagging.
```suggestion
* `guest_vlan_allowed` - (Optional; *v3.11+*) True if Network allows guest VLAN tagging.
```

2023-08-07 06:01 UTC, dataclouder commented on website/docs/r/network_isolated_v2.html.markdown
> +* `guest_vlan_allowed` - (Optional) True if Network allows guest VLAN tagging.
```suggestion
* `guest_vlan_allowed` - (Optional; *v3.11+*) True if Network allows guest VLAN tagging.
```

2023-08-07 06:01 UTC, dataclouder commented on website/docs/r/network_routed.html.markdown
> +* `guest_vlan_allowed` - (Optional) True if Network allows guest VLAN tagging.
```suggestion
* `guest_vlan_allowed` - (Optional; *v3.11+*) True if Network allows guest VLAN tagging.
```

2023-08-07 06:01 UTC, dataclouder commented on website/docs/r/network_routed_v2.html.markdown
> +* `guest_vlan_allowed` - (Optional) True if Network allows guest VLAN tagging.
```suggestion
* `guest_vlan_allowed` - (Optional; *v3.11+*) True if Network allows guest VLAN tagging.
```

2023-08-17 11:23 UTC, Didainius commented
@s-winkelhofer - a few comments/asks:

I have tested the `v2` resources and looks to be working great. 

> @Didainius thank you. We are only using the `_v2` resources. I added the feature to the `non _v2` resources for completeness reasons.

If you don't mind I'd like to keep the original resources (without "_v2") they way they are (without new field). They are using legacy API and we don't intend to maintain them much apart from critical bugs. The reality is that they should be deprecated at some point and then removed later on. They are using legacy XML API, while the `v2` ones use the new OpenAPI endpoints. This was the reason for the introduction of `v2` resources.

I also have a tiny patch that does two things:
* It removes `guest_vlan_allowed = false` in a few places for test configuration (which is the default value anyway because Go boolean becomes `false` by default). This allows for better compatibility check (we don't want to cause any plan issues for people that are upgrading here)
* It adds a few lines to `skip-upgrade-tests.txt` - we're using this for what are called `upgrade` tests. These particular files check if schema or resource changed and it does (because `guest_vlan_allowed` field is added)

You should be able to pick it here https://gist.github.com/Didainius/d7af37d898c8681ef7a9f3b1b487fe66 , save it to a file and then do `git apply filename`. I can't make a PR to your branch directly because the CLAbot we have doesn't like coauthored PRs.

2023-11-27 06:49 UTC, Didainius commented
@s-winkelhofer ,
I am working on to remove the field from `v1` resources as we want to pull this one in for 3.11 release.

2023-11-28 07:55 UTC, Didainius commented
Closing in favor of #1168

2023-11-28 07:55 UTC, closed without merging