vcd/resource_vcd_vapp_network.go: Check for RESOLVED status for powering off vApp
vmware/terraform-provider-vcd pull request #1092
Opened 2023-07-20 11:52 UTC by NilsBusche

Closes #1091

2023-07-26 06:04 UTC, Didainius commented
@NilsBusche ,
Thanks for the PR!. I'd like to clarify when do you get it to `RESOLVED` state?
I will have to reinforce it with a test so want to find out how to replicate the problem

2023-07-26 06:06 UTC, NilsBusche commented
@Didainius vApp gets into RESOLVED, if you create it without any VMs in it or if you have a stopped vApp and remove all VMs from it.

2023-07-26 07:30 UTC, Didainius commented
Thanks! 

I have created a test that fails without your patch. The stupid part is that I can't make a PR to your repository as in the end it will probably ruin CLAbot (it doesn't like PRs that have multiple contributors). 
Therefore I have put the patch to a gist - https://gist.github.com/Didainius/59b072055eb30949eed84dfe6c6a8621

Could you do a `git apply patch.git` after downloading that file. After it is here, we should be able to run a broader test suite to verify that nothing got broken along the way.

2023-07-26 07:42 UTC, NilsBusche commented
I've added the patch

2023-07-27 11:29 UTC, Didainius approved these changes
Thanks. I am good with it. I ran tests with `vm vapp network` tags on 10.3.3 (which wouldn't be impacted anyway) and 10.4.2.

2023-08-06 07:01 UTC, dataclouder requested changes

2023-08-07 07:44 UTC, NilsBusche commented on vcd/resource_vcd_vapp_network_test.go
> +	if vcdClient.Client.APIVCDMaxVersionIs("< 37.1") {
Changed

2023-08-07 07:44 UTC, NilsBusche commented on vcd/resource_vcd_vapp_network_test.go
> +	}
Changed

2023-08-07 07:44 UTC, NilsBusche commented on vcd/resource_vcd_vapp_network_test.go
> +
Changed

2023-08-07 07:47 UTC, dataclouder approved these changes
Thanks for your contribution!

2023-08-17 11:25 UTC, lvirbalas approved these changes
Thank you for contributing!

2023-08-21 15:02 UTC, adezxc approved these changes

2023-08-24 08:43 UTC, merged

2023-08-24 08:43 UTC, Didainius commented
Thank you @NilsBusche , this is merged and set for `3.11`