Add IPsec VPN Tunnel support
vmware/terraform-provider-vcd pull request #678
Opened 2021-06-16 06:19 UTC by Didainius

WIP - not for reviews yet

2021-06-25 13:51 UTC, dataclouder requested changes
A few small changes required

2021-06-25 13:51 UTC, dataclouder commented on vcd/datasource_vcd_nsxt_ipsec_vpn_tunnel.go
> +							Required:    true,
```suggestion
							Computed:    true,
```

2021-06-25 13:51 UTC, dataclouder commented on vcd/datasource_vcd_nsxt_ipsec_vpn_tunnel.go
> +							Optional: true,
```suggestion
							Computed: true,
```

2021-06-25 13:51 UTC, dataclouder commented on vcd/datasource_vcd_nsxt_ipsec_vpn_tunnel.go
> +			// Computed attributes from here
Comment not needed for data source

2021-06-25 13:51 UTC, dataclouder commented on vcd/resource_vcd_nsxt_app_port_profile.go
> +			desinationPortSet := convertStringsTotTypeSet(value.DestinationPorts)
```suggestion
			destinationPortSet := convertStringsTotTypeSet(value.DestinationPorts)
```

2021-06-25 13:51 UTC, dataclouder commented on vcd/resource_vcd_nsxt_ipsec_vpn_tunnel.go
> +		return diag.Errorf("error retrieving NSX-T IPsec VPN Tunnel configuration for deletion: %s", err)
```suggestion
		return diag.Errorf("error retrieving NSX-T IPsec VPN Tunnel configuration: %s", err)
```

2021-06-25 18:22 UTC, Didainius commented on vcd/datasource_vcd_nsxt_ipsec_vpn_tunnel.go
> +							Required:    true,
Fixed.

2021-06-25 18:22 UTC, Didainius commented on vcd/datasource_vcd_nsxt_ipsec_vpn_tunnel.go
> +							Optional: true,
Fixed.

2021-06-25 18:22 UTC, Didainius commented on vcd/datasource_vcd_nsxt_ipsec_vpn_tunnel.go
> +			// Computed attributes from here
Fixed.

2021-06-25 18:22 UTC, Didainius commented on vcd/resource_vcd_nsxt_app_port_profile.go
> +			desinationPortSet := convertStringsTotTypeSet(value.DestinationPorts)
Fixed.

2021-06-25 18:22 UTC, Didainius commented on vcd/resource_vcd_nsxt_ipsec_vpn_tunnel.go
> +		return diag.Errorf("error retrieving NSX-T IPsec VPN Tunnel configuration for deletion: %s", err)
Fixed.

2021-06-26 19:10 UTC, dataclouder approved these changes

2021-06-27 17:44 UTC, merged