(417): update hcl syntax in doc examples
vmware/terraform-provider-vcd pull request #705
Opened 2021-08-25 06:46 UTC by vladdoster

- format hcl code blocks via `terraform fmt`
- update attribute syntax due to addition of [first class
  expressions](https://www.terraform.io/upgrade-guides/0-12.html#first-class-expressions) in Terraform v0.12

closes   #417 

Signed-off-by: Vladislav Doster <mvdoster@gmail.com>

2021-08-25 10:19 UTC, dataclouder requested changes
Apart from a change request, there are several lines (usually the last line in a block of changes) that are shown as changed although I could not see the difference with the original. I don't know if this is a GitHub glitch or an invisible character being added where it shouldn't.
Please investigate

2021-08-25 10:19 UTC, dataclouder commented on website/docs/d/external_network.html.markdown
> +  network_name = "${data.vcd_external_network.tf-external-network.name}"
```suggestion
  network_name = data.vcd_external_network.tf-external-network.name
```

2021-08-25 10:19 UTC, dataclouder commented on website/docs/d/independent_disk.html.markdown
> +All attributes defined in [independent disk](/docs/providers/vcd/r/independent_disk.html#attribute-reference) are supported.
What was changed in this line? Can't see the diff.

2021-08-25 10:19 UTC, dataclouder commented on website/docs/d/nsxt_tier0_router.html.markdown
> +* `is_assigned` - Boolean value reflecting if Tier-0 router is already consumed by external network.
What was changed in this line? Can't see the diff.

2021-08-25 10:19 UTC, dataclouder commented on website/docs/d/right.html.markdown
> +rights work together.
What was changed in this line? Can't see the diff.

2021-08-25 10:19 UTC, dataclouder commented on website/docs/d/role.html.markdown
> +rights work together.
What was changed in this line? Can't see the diff.

2021-08-25 10:19 UTC, dataclouder commented on website/docs/d/storage_profile.html.markdown
> +This data source exports only `id` field.
What was changed in this line? Can't see the diff.

2021-08-25 10:19 UTC, dataclouder commented on website/docs/r/edgegateway_settings.html.markdown
> +further operations.
What was changed in this line? Can't see the diff.

2021-08-25 10:19 UTC, dataclouder commented on website/docs/r/lb_app_rule.html.markdown
> +EOT
What was changed in this line? Can't see the diff.

2021-08-25 10:19 UTC, dataclouder commented on website/docs/r/nsxt_ipsec_vpn_tunnel.html.markdown
> +VDC named `my-org-vdc`.
What was changed in this line? Can't see the diff.

2021-08-25 10:19 UTC, dataclouder commented on website/docs/r/nsxv_firewall_rule.html.markdown
> +```
What was changed in this line? Can't see the diff.

2021-08-25 10:19 UTC, dataclouder commented on website/docs/r/role.html.markdown
> +rights work together.
What was changed in this line? Can't see the diff.

2021-08-25 10:19 UTC, dataclouder commented on website/docs/r/vapp_firewall_rules.html.markdown
> +```
What was changed in this line? Can't see the diff.

2021-08-25 10:19 UTC, dataclouder commented on website/docs/r/vapp_nat_rules.html.markdown
> +```
What was changed in this line? Can't see the diff.

2021-08-25 10:19 UTC, dataclouder commented on website/docs/r/vapp_network.html.markdown
> +which is configured in organization named `my-org` and VDC named `my-org-vdc`.
What was changed in this line? Can't see the diff.

2021-08-25 10:19 UTC, dataclouder commented on website/docs/r/vapp_org_network.html.markdown
> +`vapp-name` which is configured in organization named `my-org` and VDC named `my-org-vdc`.
What was changed in this line? Can't see the diff.

2021-08-25 10:19 UTC, dataclouder commented on website/docs/r/vm.html.markdown
> +```
What was changed in this line? Can't see the diff.

2021-08-25 10:19 UTC, dataclouder commented on website/docs/r/vm_internal_disk.html.markdown
> +```
What was changed in this line? Can't see the diff.

2021-08-25 10:19 UTC, dataclouder commented on website/docs/r/vm_sizing_policy.html.markdown
> +```
What was changed in this line? Can't see the diff.

2021-08-28 02:16 UTC, vladdoster commented
Thanks for taking the time to look over this large PR, @dataclouder!

2021-08-30 05:39 UTC, Didainius reviewed
Thanks for this improvement. I have this one comment where I think the tool left out unneeded comment.

2021-08-30 05:39 UTC, Didainius commented on website/docs/guides/data_source_filters.html.markdown
> +# TF-UPGRADE-TODO: Block type was not recognized, so this block and its contents were not automatically upgraded.
This was injected by the tool here and I guess it doesn't make sense as it is just an excerpt, not a complete HCL.

2021-08-30 14:14 UTC, lvirbalas approved these changes
LGTM! Thank you for your contribution!

2021-08-31 06:07 UTC, Didainius commented on website/docs/guides/data_source_filters.html.markdown
> +# TF-UPGRADE-TODO: Block type was not recognized, so this block and its contents were not automatically upgraded.
I will use the opportunity for one more tiny thing. This is a very good user facing cleanup and it deserves a changelog note :)

Could you add a `705-improvements.md` file to `.changes/v3.4.0` and put inside a note. Feel free to grab inspiration from any other notes files there. 

Thank you!

2021-09-09 12:24 UTC, Didainius commented on website/docs/guides/data_source_filters.html.markdown
> +# TF-UPGRADE-TODO: Block type was not recognized, so this block and its contents were not automatically upgraded.
Ping!

2021-09-14 13:29 UTC, Didainius commented on website/docs/guides/data_source_filters.html.markdown
> +# TF-UPGRADE-TODO: Block type was not recognized, so this block and its contents were not automatically upgraded.
Thanks for the contributoin - I am going to merge it and add a changelog note in a separate pr.

2021-09-14 13:30 UTC, Didainius approved these changes

2021-09-14 13:30 UTC, merged