Fix enable_ip_masquerade handling in vcd_vapp_nat_rules resource
vmware/terraform-provider-vcd pull request #784
Opened 2022-02-10 07:07 UTC by vbauzysvmware

Fix for: https://github.com/vmware/terraform-provider-vcd/issues/759

The issue was that treating values was vice versa. On reading and for creating/updating.

2022-02-14 12:18 UTC, adambarreiro approved these changes

2022-02-15 16:49 UTC, lvirbalas requested changes
- Please add a sentence to the PR description about the diag changes ("the what and why").
- The fix itself seems trivial, however surprising we had the bug there. Can you add a test that covers this?

2022-02-17 06:38 UTC, vbauzysvmware commented
> * Please add a sentence to the PR description about the diag changes ("the what and why").
> 
>     * The fix itself seems trivial, however surprising we had the bug there. Can you add a test that covers this?

Added note about additional change.
As mentioned in the description, the Test covers the issue and nothing additional to add is possible, due that when read was compromised then nothing will help. The compromised read function was confirming incorrect state.

2022-02-18 08:31 UTC, lvirbalas commented
> Added note about additional change.
Thanks, but "Also update deprecated method usages" is too abstract. Let's be more precise. Maybe something like here (in the middle of description):
https://github.com/vmware/terraform-provider-vcd/pull/786

2022-02-18 16:39 UTC, vbauzysvmware commented
> > Added note about additional change.
> 
> Thanks, but "Also update deprecated method usages" is too abstract. Let's be more precise. Maybe something like here (in the middle of description): #786

added

2022-02-21 08:02 UTC, Didainius approved these changes
Tested manually and it worked well now.

2022-02-22 07:16 UTC, lvirbalas approved these changes

2022-02-22 08:16 UTC, mikeletux approved these changes
Tested manually and it work well!

2022-02-22 11:16 UTC, merged

2022-02-22 13:02 UTC, tcinbis commented
Thanks to everyone working on this issue for resolving it so quickly! 🥳

Since we are currently depending on a workaround which I would like to get rid of soon, I am curious, if there is some timeline for when the next release with this fix?