Remove org property from vcd_vm_sizing_policy
vmware/terraform-provider-vcd pull request #843
Opened 2022-05-02 15:08 UTC by dataclouder

vcd_vm_sizing_policy is a provider resource. It does not need an
organization. This change deprecates the `org` property and ignores it
if used.

2022-05-04 07:05 UTC, vbauzysvmware approved these changes

2022-05-04 07:39 UTC, adambarreiro approved these changes

2022-05-04 12:28 UTC, Didainius approved these changes

2022-05-05 07:30 UTC, mikeletux approved these changes

2022-05-05 09:06 UTC, lvirbalas requested changes

2022-05-05 09:06 UTC, lvirbalas commented on .changes/v3.7.0/853-improvements.md
> +* `datasource/vcd_vm_sizing_policy`: remove unneeded `org` property [GH-853]
Just so our users don't panic :)

```suggestion
* `resource/vcd_vm_sizing_policy`: remove (deprecate) unneeded `org` property [GH-853]
* `datasource/vcd_vm_sizing_policy`: remove (deprecate) unneeded `org` property [GH-853]
```

2022-05-05 11:29 UTC, dataclouder commented on .changes/v3.7.0/853-improvements.md
> +* `datasource/vcd_vm_sizing_policy`: remove unneeded `org` property [GH-853]
done

2022-05-05 11:51 UTC, lvirbalas approved these changes
Looks great!

2022-05-05 12:41 UTC, merged